name: ROS2 CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install ROS2
      run: |
        sudo apt update && sudo apt install curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
        sudo apt update && sudo apt install ros-humble-desktop

    - name: Environment setup
      run: |
        echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt update
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro humble -y

    - name: Build the package
      run: |
        . /opt/ros/humble/setup.bash
        colcon build

    - name: Run tests
      run: |
        . /opt/ros/humble/setup.bash
        colcon test
